version: '3'
services:

##################################################################
#  HORNET - Stardust                                             #
##################################################################

  hornet:
    healthcheck:
          retries: 150
